spring:
  profiles:
    active: dev
spotify:
  api-url: https://api.spotify.com
  accounts-api-url: https://accounts.spotify.com
  user-permission-url: ${spotify.accounts-api-url}/authorize
  scopes: user-read-private user-read-email
  callbackUrl: ${base-url}/auth/callback