spring:
  security:
    oauth2:
      client:
        registration:
          wiremock:
            provider: wiremock
            authorization-grant-type: authorization_code
            scope: email
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            clientId: wm
            clientSecret: whatever
        provider:
#          mocklab:
#            authorization-uri: https://oauth.mocklab.io/oauth/authorize
#            token-uri: https://oauth.mocklab.io/oauth/token
#            user-info-uri: https://oauth.mocklab.io/userinfo
#            user-name-attribute: sub
#            jwk-set-uri: https://oauth.mocklab.io/.well-known/jwks.json

          wiremock:
            authorization-uri: http://localhost:8077/oauth/authorize
            token-uri: http://localhost:8077/oauth/token
            user-info-uri: http://localhost:8077/me
            user-name-attribute: sub

